from dotenv import load_dotenv
import os

load_dotenv()

# Azure OpenAI
AZURE_OPENAI_ENDPOINT     = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_KEY      = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_API_VERSION  = os.getenv("AZURE_OPENAI_API_VERSION", "2024-02-01")
EMBEDDING_DEPLOYMENT      = os.getenv("AZURE_OPENAI_EMBEDDING_DEPLOYMENT")
CHAT_DEPLOYMENT           = os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT")

# Azure AI Search
AZURE_SEARCH_ENDPOINT     = os.getenv("AZURE_SEARCH_ENDPOINT")
AZURE_SEARCH_API_KEY      = os.getenv("AZURE_SEARCH_API_KEY")
AZURE_SEARCH_INDEX_NAME   = os.getenv("AZURE_SEARCH_INDEX_NAME", "enterprise-rag-index")
