"""
Stage 3b — Generator + Self Checker
-------------------------------------
Sends the assembled prompt to GPT-4o and gets an answer.
Then runs a self-check to verify the answer is grounded
in the retrieved context — not hallucinated.

Self-Check Logic:
  A second lightweight GPT-4o call reads:
    - The context
    - The generated answer
  And decides: is every claim in the answer supported by the context?

Usage:
    python generation/generator.py
"""

from pathlib import Path
from openai import AzureOpenAI
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
import sys
import time
import json

sys.path.append(str(Path(__file__).parent.parent))
from retrieval.reranker import run_reranker
from generation.prompt_builder import build_prompt
import config

console = Console()

# ── Azure OpenAI client ──────────────────────────────────────────────
client = AzureOpenAI(
    azure_endpoint = config.AZURE_OPENAI_ENDPOINT,
    api_key        = config.AZURE_OPENAI_API_KEY,
    api_version    = config.AZURE_OPENAI_API_VERSION
)

# ── Self checker prompt ───────────────────────────────────────────────
SELF_CHECK_PROMPT = """You are a strict fact-checker for an HR policy assistant.

You will be given:
1. CONTEXT: The policy documents retrieved from the database
2. ANSWER: The answer generated by the assistant

Your job is to verify if every factual claim in the ANSWER
is directly supported by the CONTEXT.

Respond with ONLY a JSON object in this exact format:
{
  "verdict": "GROUNDED" or "HALLUCINATION",
  "confidence": 0.0 to 1.0,
  "reason": "one line explanation",
  "unsupported_claims": ["claim1", "claim2"] or []
}

Rules:
- GROUNDED = every claim in the answer comes from the context
- HALLUCINATION = answer contains facts not present in context
- Be strict — even small invented details count as hallucination
- Nothing else. No markdown. No extra text."""


def generate_answer(prompt_data: dict) -> dict:
    """
    Send assembled prompt to GPT-4o and get an answer.
    Logs latency, token usage from API response.
    """
    console.print("\n[bold yellow]Step 1: Sending Prompt to GPT-4o[/bold yellow]\n")
    console.print(f"  [dim]Model      : {config.CHAT_DEPLOYMENT}[/dim]")
    console.print(f"  [dim]Tokens in  : {prompt_data['total_tokens']}[/dim]")
    console.print(f"  [dim]Temperature: 0.0 (deterministic — no creativity for policy answers)[/dim]\n")

    start = time.time()

    try:
        response = client.chat.completions.create(
            model       = config.CHAT_DEPLOYMENT,
            messages    = prompt_data["messages"],
            max_tokens  = 300,
            temperature = 0.0   # deterministic — policy answers must be consistent
        )
    except Exception as e:
        console.print(f"  [red]✗ GPT-4o call failed: {str(e)[:100]}[/red]")
        return None

    latency       = round(time.time() - start, 3)
    answer        = response.choices[0].message.content.strip()
    prompt_tokens = response.usage.prompt_tokens
    answer_tokens = response.usage.completion_tokens
    total_tokens  = response.usage.total_tokens

    console.print(f"  [green]✓ Response received ({latency}s)[/green]")
    console.print(f"  [dim]  Prompt tokens   : {prompt_tokens}[/dim]")
    console.print(f"  [dim]  Answer tokens   : {answer_tokens}[/dim]")
    console.print(f"  [dim]  Total tokens    : {total_tokens}[/dim]")

    # Print the raw answer
    console.print(f"\n[bold yellow]📢 GPT-4o Raw Answer:[/bold yellow]\n")
    console.print(Panel(
        f"[bold white]{answer}[/bold white]",
        title=f"Generated Answer ({answer_tokens} tokens, {latency}s)",
        border_style="green"
    ))

    return {
        "answer"        : answer,
        "latency"       : latency,
        "prompt_tokens" : prompt_tokens,
        "answer_tokens" : answer_tokens,
        "total_tokens"  : total_tokens
    }


def run_self_check(answer: str, context_block: str) -> dict:
    """
    Second LLM call to verify the answer is grounded in context.
    This is the hallucination detection step.
    """
    console.print(f"\n[bold yellow]Step 2: Self-Check — Hallucination Detection[/bold yellow]\n")
    console.print(f"  [dim]Sending answer + context to self-checker...[/dim]")
    console.print(f"  [dim]This is a second GPT-4o call — reads query + answer together[/dim]\n")

    check_input = (
        f"CONTEXT:\n{context_block}\n\n"
        f"ANSWER:\n{answer}"
    )

    start = time.time()

    try:
        response = client.chat.completions.create(
            model    = config.CHAT_DEPLOYMENT,
            messages = [
                {"role": "system", "content": SELF_CHECK_PROMPT},
                {"role": "user",   "content": check_input}
            ],
            max_tokens  = 150,
            temperature = 0.0
        )
    except Exception as e:
        console.print(f"  [yellow]⚠ Self-check failed: {str(e)[:80]} — skipping[/yellow]")
        return {"verdict": "UNKNOWN", "confidence": 0.0, "reason": "self-check error"}

    latency  = round(time.time() - start, 3)
    raw      = response.choices[0].message.content.strip()

    console.print(f"  [dim]Self-checker response ({latency}s): {raw}[/dim]\n")

    try:
        result             = json.loads(raw)
        verdict            = result.get("verdict", "UNKNOWN")
        confidence         = result.get("confidence", 0.0)
        reason             = result.get("reason", "")
        unsupported_claims = result.get("unsupported_claims", [])

        if verdict == "GROUNDED":
            console.print(Panel(
                f"[bold green]✅ GROUNDED[/bold green]\n"
                f"Confidence        : {confidence}\n"
                f"Reason            : {reason}\n"
                f"Unsupported claims: None",
                title="Self-Check Verdict",
                border_style="green"
            ))
        else:
            console.print(Panel(
                f"[bold red]⚠️  HALLUCINATION DETECTED[/bold red]\n"
                f"Confidence        : {confidence}\n"
                f"Reason            : {reason}\n"
                f"Unsupported claims: {unsupported_claims}",
                title="Self-Check Verdict",
                border_style="red"
            ))

        return {
            "verdict"           : verdict,
            "confidence"        : confidence,
            "reason"            : reason,
            "unsupported_claims": unsupported_claims,
            "latency"           : latency
        }

    except json.JSONDecodeError:
        console.print(f"  [yellow]⚠ Could not parse self-check response[/yellow]")
        return {"verdict": "UNKNOWN", "confidence": 0.0, "reason": "parse error"}


def run_generation(query: str) -> dict:
    """
    Full generation pipeline:
    1. Run reranker to get parent chunks
    2. Build prompt
    3. Generate answer
    4. Self-check for hallucinations
    5. Print full summary
    """
    console.rule("[bold cyan]Stage 3b — Generator + Self Checker[/bold cyan]")
    console.print(f"\n[bold]🔍 Query:[/bold] [yellow]\"{query}\"[/yellow]\n")

    # ── Step 1: Retrieve context ─────────────────────────────────────
    console.print("[bold yellow]Step 0: Running Retrieval Pipeline[/bold yellow]")
    console.print("[dim]  (guardrail → HyDE → hybrid search → reranker → parents)[/dim]\n")
    retrieval_result = run_reranker(query)
    parents          = retrieval_result["parents"]
    console.print(f"\n  [green]✓ Retrieved {len(parents)} parent chunks ({retrieval_result['total_tokens']} tokens)[/green]\n")

    # ── Step 2: Build prompt ─────────────────────────────────────────
    prompt_data = build_prompt(query, parents)

    # ── Step 3: Generate answer ──────────────────────────────────────
    generation_result = generate_answer(prompt_data)
    if not generation_result:
        return None

    # ── Step 4: Self-check ───────────────────────────────────────────
    self_check_result = run_self_check(
        answer        = generation_result["answer"],
        context_block = prompt_data["context_block"]
    )

    # ── Step 5: Final summary ────────────────────────────────────────
    console.print(f"\n[bold yellow]📊 Generation Summary[/bold yellow]\n")

    table = Table(show_lines=True, title="End-to-End Generation Stats")
    table.add_column("Metric",          style="white")
    table.add_column("Value",           style="cyan",  justify="right")

    table.add_row("Query",                  query[:50])
    table.add_row("Parent chunks used",     str(len(parents)))
    table.add_row("Context tokens",         str(prompt_data["context_tokens"]))
    table.add_row("Total prompt tokens",    str(prompt_data["total_tokens"]))
    table.add_row("Answer tokens",          str(generation_result["answer_tokens"]))
    table.add_row("Generation latency",     f"{generation_result['latency']}s")
    table.add_row("Self-check verdict",     self_check_result["verdict"])
    table.add_row("Self-check confidence",  str(self_check_result["confidence"]))
    table.add_row("Self-check latency",     f"{self_check_result.get('latency', 0)}s")

    console.print(table)

    # ── Final answer panel ───────────────────────────────────────────
    verdict_color = "green" if self_check_result["verdict"] == "GROUNDED" else "red"
    verdict_icon  = "✅" if self_check_result["verdict"] == "GROUNDED" else "⚠️"

    console.print(Panel(
        f"[bold white]{generation_result['answer']}[/bold white]\n\n"
        f"[{verdict_color}]{verdict_icon} {self_check_result['verdict']} "
        f"(confidence: {self_check_result['confidence']})[/{verdict_color}]",
        title=f"Final Answer — {query[:40]}",
        border_style=verdict_color
    ))

    console.print(f"\n[dim]Next step → run: python generation/output_guardrail.py[/dim]\n")

    return {
        "query"         : query,
        "answer"        : generation_result["answer"],
        "verdict"       : self_check_result["verdict"],
        "parents_used"  : len(parents),
        "total_tokens"  : generation_result["total_tokens"],
        "latency"       : generation_result["latency"],
        "self_check"    : self_check_result
    }


if __name__ == "__main__":
    query = "How many days of leave can I carry forward?"
    run_generation(query)